name: 'sbt-coursier-cache'
author: 'gvolpe'
description: 'one-liner sbt and coursier cache for GitHub Actions'
branding:
  icon: 'arrow-down-circle'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
